### ISSUE TITLE
Odoo v11 - Error after installing hotel_channel_connector_wubook

### ISSUE THREAD

**Issue by vbezl** [hootel/hootel#82]
If I install hotel and hotel_calendar - everything works fine, but after installing hotel_channel_connector_wubook - the following error appears.
Can you please help to identify what am I missing?

```
2019-01-22 16:08:38,363 24725 ERROR odoo_ent_mpms odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/Users/bezl/Documents/htdocs/odoo/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/Users/bezl/Documents/htdocs/odoo/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/bezl/Documents/htdocs/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'odoo_ent_mpms'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/odoo/Documents/htdocs/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/modules/loading.py", line 478, in load_modules
    model._register_hook()
  File "/Users/odoo/Documents/htdocs/odoo/addons-custom/queue/queue_job/models/base.py", line 28, in _register_hook
    self.env['queue.job.function']._register_job(self, job_method)
  File "/Users/odoo/Documents/htdocs/odoo/addons-custom/queue/queue_job/models/queue_job.py", line 413, in _register_job
    channel = self._find_or_create_channel(job_method.default_channel)
  File "/Users/odoo/Documents/htdocs/odoo/addons-custom/queue/queue_job/models/queue_job.py", line 405, in _find_or_create_channel
    'parent_id': parent_channel.id,
  File "/Users/odoo/Documents/htdocs/odoo/addons-custom/connector/component_event/models/base.py", line 97, in create
    self._event('on_record_create').notify(record, fields=fields)
  File "/Users/odoo/Documents/htdocs/odoo/addons-custom/connector/component_event/models/base.py", line 91, in _event
    return collecter.collect_events(name)
  File "/Users/odoo/Documents/htdocs/odoo/addons-custom/connector/component_event/components/event.py", line 263, in collect_events
    events = self._init_collected_events(self._collect_events(name))
  File "/usr/local/lib/python3.7/site-packages/cachetools/__init__.py", line 82, in wrapper
    k = key(*args, **kwargs)
TypeError: <lambda>() missing 1 required positional argument: 'name'
2019-01-22 16:08:38,365 24725 INFO odoo_ent_mpms werkzeug: 127.0.0.1 - - [22/Jan/2019 16:08:38] "POST /web/webclient/version_info HTTP/1.1" 500 -
2019-01-22 16:08:38,369 24725 ERROR odoo_ent_mpms werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/service/server.py", line 260, in app
    return self.app(e, s)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/http.py", line 1319, in __call__
    return self.dispatch(environ, start_response)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/http.py", line 1293, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/http.py", line 1474, in dispatch
    odoo.registry(db).check_signaling()
  File "/Users/odoo/Documents/htdocs/odoo/odoo/__init__.py", line 76, in registry
    return modules.registry.Registry(database_name)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/modules/registry.py", line 61, in __new__
    return cls.new(db_name)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/modules/loading.py", line 478, in load_modules
    model._register_hook()
  File "/Users/odoo/Documents/htdocs/odoo/addons-custom/queue/queue_job/models/base.py", line 28, in _register_hook
    self.env['queue.job.function']._register_job(self, job_method)
  File "/Users/odoo/Documents/htdocs/odoo/addons-custom/queue/queue_job/models/queue_job.py", line 413, in _register_job
    channel = self._find_or_create_channel(job_method.default_channel)
  File "/Users/odoo/Documents/htdocs/odoo/addons-custom/queue/queue_job/models/queue_job.py", line 405, in _find_or_create_channel
    'parent_id': parent_channel.id,
  File "/Users/odoo/Documents/htdocs/odoo/addons-custom/connector/component_event/models/base.py", line 97, in create
    self._event('on_record_create').notify(record, fields=fields)
  File "/Users/odoo/Documents/htdocs/odoo/addons-custom/connector/component_event/models/base.py", line 91, in _event
    return collecter.collect_events(name)
  File "/Users/odoo/Documents/htdocs/odoo/addons-custom/connector/component_event/components/event.py", line 263, in collect_events
    events = self._init_collected_events(self._collect_events(name))
  File "/usr/local/lib/python3.7/site-packages/cachetools/__init__.py", line 82, in wrapper
    k = key(*args, **kwargs)
TypeError: <lambda>() missing 1 required positional argument: 'name'
```

**Comment by pabloqb** [comment]
Dear vbezl,

it could be related to cachetool version.
Could you check that `cachetools` version is between `>=2.0.1,<3.0.0`?. 

Best regards,
Pablo.

**Comment by vbezl** [comment]
It's (3.0.0)
Should I try to install earlier version, right?

**Comment by pabloqb** [comment]
You __should__,

It is actually a OCA/connector requirement. You can find more information at https://github.com/OCA/connector/issues/311.

Best Regards,
Pablo.

**Comment by vbezl** [comment]
It works, thanks a lot!
