### ISSUE TITLE
Odoo v11 - Error saving pricing changes in hotel management calendar after installation of hotel_channel_connector module

### ISSUE THREAD

**Issue by vbezl** [hootel/hootel#83]
Hi, this one is probably in hotel_channel_connector module.
If I install only "hotel" and "hotel_calendar" - pricing updates are saved without errors.
Then if I install hotel_channel_connector - the same pricing updates shows error:

Error:
```
Odoo Server Error

Traceback (most recent call last):
  File "/Users/odoo/Documents/htdocs/odoo/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/odoo/Documents/htdocs/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/Users/odoo/Documents/htdocs/odoo/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/Users/odoo/Documents/htdocs/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/Users/odoo/Documents/htdocs/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/Users/odoo/Documents/htdocs/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
TypeError: save_changes() missing 1 required positional argument: 'availability'
```

**Comment by Tardo** [comment]
Hi! thanks for report... Currently we are working on changes in "availability management" (follow this PR: https://github.com/hootel/hootel/pull/81)

Cheers!

**Comment by vbezl** [comment]
I see, thanks for your answer! Will follow PR #81
